sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t stephengrider/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stephengrider/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: jLSuY4AuRAL0qA8+YfwVKPr9BuYM/ovmyhZPQCXi
  secret_access_key:
    secure: 8G]R}%N&wD-S
  region: "ap-south-1"
  app: "dockerreact"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-881517042792"
