sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t preetham159/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true preetham159/docker-react npm run test
